### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by hunter** [pachyderm/pachyderm#1068]
We're starting to use [Helm](https://github.com/kubernetes/helm) a lot more for deployment and was thinking it would be good to have Pachyderm as a chart.

Does it make sense to have an alternative to the `pachctl deploy` command? There seems to be some overlap with lifecycle management but I haven't looked close enough at the code to see if it is doing anything unusual during deployment.

**Comment by jdoliner** [comment]
Yeah I think a Helm chart could make sense for us. Basically all we'd need to do is turn `pachctl deploy` into a template. All that `pachctl deploy` does is generate a k8s manifest and send it off to k8s. If you want to get this manifest in you can add the `--dry-run` flag to write it to stdout. You could in theory roll your own helm chart from that if you need compatibility with Helm immediately.

**Comment by hunter** [comment]
Great! I got the dry-run output and started converting. One thing that I wasn't sure of was support for namespaces. Does pachctl (and pachd?) only support the `default` namespace?

Also, is there a reason for Replication Controllers instead of Deployments?

**Comment by derekchiang** [comment]
@hunter We currently only support the `default` namespace, although we really should be using our own namespace.  I think there's an issue for that somewhere.

AFAIK there's no reason why we can't use Deployments.  We just haven't got around to it since it's a relatively new feature.

**Comment by derekchiang** [comment]
@hunter actually I made a mistake.  You can actually deploy Pachyderm to any namespace you want by using the `--namespace` flag when you use `kubectl create`.

**Comment by hunter** [comment]
I've tried out a basic version of a deployment with Helm - https://github.com/AcalephStorage/charts/tree/pachyderm/incubator/pachyderm

It seems to work but found that I needed to hardcode resource names to ensure that `pachd` could find `rethink`. `pachctl` also seems to break when launched in a custom namespace so had to work around by querying for the pod name and port-forwarding through `kubectl`.

**Comment by JoeyZwicker** [comment]
+1 to this issue from the PhenoMeNal team

**Comment by jonandernovella** [comment]
+1. It would be very handy

**Comment by dwhitena** [comment]
+1 from several users in users Slack.

**Comment by dwhitena** [comment]
Had a user recommend this as well:

```
user [8:56 AM] 
Check out Draft as well by Microsoft.

[8:56] 
Helm is for releasing. Draft is for development :slightly_smiling_face:

[8:58] 
@dwhitena See https://github.com/Azure/draft
```

**Comment by gabrielgrant** [comment]
PharmBio has a Helm chart they are using for deployment here: https://github.com/pharmbio/pbcharts/tree/master/pachyderm

**Comment by Vlaaaaaaad** [comment]
Since https://github.com/kubernetes/charts/tree/master/stable/pachyderm exists, should this not be closed? Are there any other things missing from the chart?

**Comment by dwhitena** [comment]
Yes, I think we can close this now @Vlaaaaaaad. Thanks for the reminder! This chart covers the major deployments, both cloud and local.

**Comment by gabrielgrant** [comment]
That chart doesn't seem to have any support for the dashboard or HTTP interface to PFS. Unfortunately it seems to have been taken offline, but I believe the PharBio chart did have dash support (though it required using a custom domain IIRC), but also lacked the PFS HTTP interface.

**Comment by naztyroc** [comment]
Everyone,

I've been working on adding Dashboard functionality to the official helm chart, via [PR](https://github.com/kubernetes/charts/pull/4159/commits). There is one issue I presented to @gabrielgrant which was the dashboard needing http://<clusterip>:<nodeport>/?port=<pachd-nodeport>.

**Comment by jonandernovella** [comment]
Hi @naztyroc. I also worked on this. Please find my implementation details here: https://github.com/pharmbio/pbcharts/tree/master/pachyderm/templates

Cheers!

**Comment by gabrielgrant** [comment]
@jonandernovella oh, sweet, it's back! that repo was offline for a while, wasn't it?

**Comment by jonandernovella** [comment]
@gabrielgrant Yes, it was. I am sorry for the inconveniences
!

**Comment by naztyroc** [comment]
@jonandernovella thanks for the idea of using an ingress in the build, good stuff!

**Comment by gabrielgrant** [comment]
@jonandernovella no worries, just wanted to make sure i wasn't going crazy :P thanks for putting it back up!

Hoping we can merge your helm chart design with what i've been working on with @naztyroc (ie based on the official helm chart) to get a best-in-class recommendation for how dash deployment should work with helm. IIRC, we worked on getting the dash working with your helm chart sometime last summer. To confirm is that still working for you today? One feature i don't believe it supports is exposing the PFS-over-HTTP API, which is used for file download. Not sure if there are other things missing?

**Comment by jonandernovella** [comment]
@gabrielgrant Hehe. I didn't test it for a wee now. But feel free to try it. I remember that I used to access the by navigating to: `http://<dash-svc-name>/?host=<grpc-svc-name>&port=80`.
And yeah, I think we did not enable the PFS-over-HTTP API yet.

**Comment by thedrow** [comment]
Since we do have a [helm chart](https://github.com/kubernetes/charts/tree/master/stable/pachyderm) we should close this issue.

**Comment by JoeyZwicker** [comment]
@gabrielgrant @jonandernovella is the Dash part of the helm chart all sorted out or still a WIP?

**Comment by thedrow** [comment]
@jonandernovella It's easy enough to add to the Helm package.
You can use a conditional on a variable which defaults to false.

**Comment by jonandernovella** [comment]
@thedrow Agree! Feel free to make a PR .

**Comment by LaurentGoderre** [comment]
@thedrow is there a way to use another version of pachydem with that helm chart. I am experiencing a lot of issues that have already been fixed in later v1.7.x versions.

**Comment by gabrielgrant** [comment]
@LaurentGoderre the helm chart hasn't been updated to 1.8 yet (tracked in #3438), in part because no one has gotten around to it yet (so if you wanted to submit a PR that would be greatly appreciated! :wink:  ) but also in part because it isn't clear how migrations from earlier versions should be handled with helm (tracked in #3439)

**Comment by LaurentGoderre** [comment]
@gabrielgrant I created a PR to update the chart to 1.7.11 which would solve a lot already. I'll take a look at helping with a 1.8 chart as well!

PS I'm also working on a pachctl docker image

**Comment by jonandernovella** [comment]
@LaurentGoderre Updating the chart to default 1.7.11 doesn't solve any problem. You can configure the chart to pull the version you want from the values manifest file.

**Comment by jonandernovella** [comment]
@gabrielgrant There is some conflict with the ENV vars wrt the storage backend. Changing that should do the trick to make the chart work again on 1.8+

**Comment by LaurentGoderre** [comment]
@jonandernovella yes but if you do the basic `helm install` from the README like I didn't you end up with an old version with bugs that have long been fixed.

**Comment by jonandernovella** [comment]
@LaurentGoderre Sure. Still I don't think that's enough to make a new release, given that you can easily change the version...

**Comment by LaurentGoderre** [comment]
IMHO, the developer experience gain are well worth it but at the minimum I think the doc should make it clearer about how to use more recent versions

**Comment by JoeyZwicker** [comment]
I agree with @LaurentGoderre on this I think. 

@LaurentGoderre Pachyderm has plans to make this Helm chart officially supported, which will involve making it more user friendly and keeping it updated as part of our official release process. We haven't quite gotten there yet, so our continued thanks to @jonandernovella and others for maintaining the chart in the interim.

**Comment by jonandernovella** [comment]
@LaurentGoderre I agree it's worth the experience gain, but this update process needs to be automated. It's not feasible manually updating the chart for every new version is released.

**Comment by LaurentGoderre** [comment]
@jonandernovella aaah! I get you on that. Would it be possible to merge my PR as we look into upgrading for 1.8 and automating this process?

**Comment by jdoliner** [comment]
Adding @chainlink as assignee since he's presently working on this.

**Comment by kyprifog** [comment]
Curious whats the status of this?

**Comment by mindthevirt** [comment]
Hey @kyprifog thanks for reaching out and wanting to get involved. The first step would be to join our Slack community: https://pachyderm-users.slack.com/. From there we can get you started and engaged with the right folks.

**Comment by kyprifog** [comment]
@mindthevirt thank you!  How do I get an invitation, it says that I need a pachyderm email address to create an account?

**Comment by mindthevirt** [comment]
doh, that's my bad. Just fill in this form and an invite will be sent out: https://www.pachyderm.com/slack/

**Comment by artem-yushkovsky** [comment]
Hello! I found that the helm repo is archived: https://github.com/helm/charts/tree/master/stable/pachyderm
But I can't see `pachyderm` in Artifact Hub: https://artifacthub.io/packages/search?page=1&ts_query_web=pachyderm

Where can I find helm charts for Pachyderm?

**Comment by chainlink** [comment]
Hi @artem-yushkovsky. The helm chart is something that is actively scheduled for next couple of months (we need it for a bunch of internal use cases as well)

**Comment by artem-yushkovsky** [comment]
@chainlink is [this](https://github.com/pachyderm/helmchart) the working directory for helm charts?
