### ISSUE TITLE
Instrument jobshim / pachd calls w user ID

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1113]
Right now any calls job shim or pachd makes won't get reported to metrics.

(More discussion here](https://github.com/pachyderm/pachyderm/pull/1106)

**Comment by derekchiang** [comment]
I think I'm a little confused because I'm not sure what the expected use of metrics is if they don't include calls from job-shim.  Shouldn't we expect the vast majority of calls to PFS/PPS be from job executions?  Am I right in understanding that right now metrics only capture calls that users manually invoke via the CLI?  If that's the case, it feels like we really should solve this issue before metrics can give us any meaningful information.

**Comment by jdoliner** [comment]
@derekchiang I think you're mostly right, although I believe we still get metrics if the user id isn't set. They're just not attributed to users.

**Comment by sjezewski** [comment]
Metrics today collects user information based on commands issued from the CLI + cluster information.

Right now any calls from jobshim (including fuse mounts created by jobshim) are not tracked at all. Same for pachd (any requests to `ListPipeline` or `ListRepo` that are called periodically).

What we have today w the user information is enough to establish some of the roadblocks in getting pachyderm up and running (e.g. we track `pachctl version` and `pachctl deploy` from the client so that if the server isn't even up ... we can see where users are struggling). Once the server is up, and API calls will be tracked/sent from the server. This will include things like `pachctl update-pipeline...` so while we won't see exactly how the pipelines are using PFS, we do get a good idea of the 'user development funnel' in broad strokes.

That said, of course we want to track more!

Oh, and if a user does `pachctl mount ...` any calls that the local fuse mount makes is tagged to that user. Which may be another interesting data point for a 'deployment' funnel.

**Comment by sjezewski** [comment]
Closing, job-shim is gone
