### ISSUE TITLE
Feature request: Don't run pipelines when updating if nothing has changed

### ISSUE THREAD

**Issue by jdelfino** [pachyderm/pachyderm#3092]
**What is the ask?**

When updating a pipeline, don't run anything if the pipeline spec has not changed.

**What is the goal / desired outcome?**

I'd like our CI/CD to be able to blindly update all pipelines if tests pass. Right now, if nothing has changed, doing that would open commit(s) on each pipeline, and each pipeline would run. This takes some time to propagate through the entire graph, and also causes all egresses to run, which can be slow for us. With frequent commits/deploys, this will cause our cluster to back up.

Ideally, pachyderm would be smart enough to notice that nothing has actually changed, and not re-run unchanged pipelines.

**If there is a way to accomplish this today via workaround, what does that require?**

I can pull the existing pipeline JSON and try to compare, but it gets ugly quickly. e.g. the input JSON uses keys with underscores, and the output JSON uses camel cased names; the output JSON has additional fields with default values filled in, etc.

**Comment by jdelfino** [comment]
Hi @gabrielgrant, thanks for the suggestion. While `extract-pipeline` does have less "extra" stuff than `inspect-pipeline --raw`, it still has all the same comparison difficulties - differing key names, different text formats, inclusion of default values, etc.

**Comment by gabrielgrant** [comment]
@jdelfino yes, definitely not much easier. Curious, though -- which key names are different? That sounds like a bug that should be fixed

**Comment by jdelfino** [comment]
All the input keys are snake_case, and all the output keys are camelCase. e.g. `parallelism_spec` vs `parallelismSpec`.

**Comment by gabrielgrant** [comment]
@jdoliner has this been fixed?

**Comment by jdoliner** [comment]
If you maintain the salt between creations of the pipeline (which `update-pipeline` does) you won't get any reprocessing, you will still get a job. That seems fine except that it redoes the merge and the egressing. The prior should be short circuiting very quickly due to 1.8 changes. And if we move the egressing step into the merge as we plan in #3223 that should shortcircuit as well.

We may want to consider an earlier short-circuit for this case.
