### ISSUE TITLE
pachctl list commit crash

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#3679]
**What happened?**:
Crash when running `pachctl list commit reads`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15f6db5]

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/server/pfs/pretty.PrintCommitInfo(0x1db1f60, 0xc000528300, 0xc00047c2a0, 0xc00047c200)
        src/server/pfs/pretty/pretty.go:108 +0xe5
github.com/pachyderm/pachyderm/src/server/pfs/cmds.Cmds.func9.2(0xc00047c2a0, 0xc00047c2a0, 0x0)
        src/server/pfs/cmds/cmds.go:379 +0x4b
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client.APIClient.ListCommitF(0x7f93c98039e0, 0xc00000e030, 0x7f93c9803ae0, 0xc00000e038, 0x7f93c9803ba8, 0xc00000e040, 0x7f93c9803c40, 0xc00000e0b0, 0x7f93c9803d00, 0xc00000e0c0, ...)
        src/server/vendor/github.com/pachyderm/pachyderm/src/client/pfs.go:301 +0x195
github.com/pachyderm/pachyderm/src/server/pfs/cmds.Cmds.func9(0xc00017f160, 0x1, 0x1, 0x0, 0x0)
        src/server/pfs/cmds/cmds.go:378 +0x3eb
github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.RunFixedArgs.func1(0xc0003618c0, 0xc00017f160, 0x1, 0x1)
        src/server/pkg/cmdutil/cobra.go:22 +0x117
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003618c0, 0xc00017f120, 0x1, 0x1, 0xc0003618c0, 0xc00017f120)
        src/server/vendor/github.com/spf13/cobra/command.go:572 +0x24a
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e38c0, 0x0, 0x0, 0x0)
        src/server/vendor/github.com/spf13/cobra/command.go:658 +0x2cc
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000e38c0, 0x1c40b80, 0x1c40b88)
        src/server/vendor/github.com/spf13/cobra/command.go:617 +0x2b
main.main.func1(0x0, 0x0)
        src/server/cmd/pachctl/main.go:20 +0x4b
main.main()
        src/server/cmd/pachctl/main.go:21 +0xc8
```

In addition, `pachctl list commit reads@master` returns `pachyderm/1.7.0/pachyderm_pfs/repos/ <repo>@master not found` which is not true since we do have a repo "reads" having a branch "master".

**How to reproduce it (as minimally and precisely as possible)?**:

```
pachctl create repo reads
pachctl put file -o reads@master:/data/myFile.txt -f path/to/file.txt
pachctl list commit reads@master //Throws error above
pachctl list commit reads        //Says that reads@master does not exist
```

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI version (use `pachctl version`):
COMPONENT           VERSION             
pachctl             1.9.0rc1            
pachd               1.8.6   

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
local: minikube

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by Tryneus** [comment]
@marcadella, thanks for reporting this!  I think this is happening because you are using a newer `pachctl` than your `pachd`.  It would help the debugging if you could provide the output of `pachctl list commit reads --raw`.

As for `pachyderm/1.7.0/pachyderm_pfs/repos/<repo>@master not found` - this was an error I made when implementing the new command format - for the meantime you should be able to use the deprecated `pachctl list-commit`, but this should be fixed for the `v1.9.0` release.  Fix is in PR #3680.

@adelelopez - this appears to be happening on the line that prints the commit's branch name, looks like `commitInfo.Branch` is `nil` - I'm pretty sure this is due to the version mismatch, but I think this is related to your changes, could you confirm?

**Comment by adelelopez** [comment]
Yeah, that's related to my change. I think the version mismatch explains it.

**Comment by marcadella** [comment]
It works fine if I use `pachctl list commit reads --raw`:
```
{
  "commit": {
    "repo": {
      "name": "reads"
    },
    "id": "bf05e8135ec140f6ab8691c6457ef04b"
  },
  "started": "2019-04-29T13:36:11.110167669Z",
  "finished": "2019-04-29T13:36:11.114161737Z",
  "sizeBytes": "3932144",
  "tree": {
    "hash": "4d26c74be1e5b41bf0d3fa5020da57cf7142dba75e0bf7b5f313041e007c23140bab687249496aceb71d2e8f1d71d395a1e59d0cf28d9462d918a804372f5ac8"
  }
}
```
However why do I get an error from pachyderm 1.7.0? As posted above my version of pachd is 1.8.6...

**Comment by Tryneus** [comment]
@marcadella - in v1.9.0, Pachyderm now associates every commit with a branch.  The v1.9.0 `pachctl` is expecting `pachd` to send this information back, but because `pachd` is v1.8.6, that information is not included and the printing fails.  For the short term, you should use the same `pachctl` version as your `pachd` version, until you've migrated your cluster to v1.9.0.

**Comment by marcadella** [comment]
@Tryneus I have now both pachctl and pachd at v1.9.0.rc1 and I still get exactly the same issues.

**Comment by Tryneus** [comment]
@marcadella - thanks for letting us know and sorry this is still a problem for you, although I couldn't reproduce this on `v1.9.0.rc1` using your steps:

```
$ pachctl create repo reads

$ pachctl put file -o reads@master:/data/myFile.txt -f file.txt

$ pachctl list commit reads@master
pachyderm/1.7.0/pachyderm_pfs/repos/ reads@master not found
# This is expected because #3680 was not included in v1.9.0.rc1

$ pachctl list commit reads
REPO  BRANCH COMMIT                           PARENT STARTED        DURATION           SIZE     
reads master caa88cb6c23d4813a2f46fd5f6994059 <none> 27 seconds ago Less than a second 1.931KiB 
```

@adelelopez - is there any migration necessary to backfill the branch information on commits?

**Comment by adelelopez** [comment]
@Tryneus There shouldn't be, it should be able to infer it if it's not present. 

@marcadella could you show me what `inspect commit` with the `--raw` flag spits out? 

In any case, it shouldn't crash if it can't find the branch. I think that's a bug I introduced when updating the pretty printer.

**Comment by marcadella** [comment]
My bad, I deleted minikube and started it again and now it works with `pachctl list commit reads`.
I guess `4be1d0f` will fix `pachctl list commit reads@master` so I close this issue.
Thanks!
