### ISSUE TITLE
Job Enters Infinite Retry Loop with 120,000 Files in the Input Repo

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6615]
I'm running one of my standard performance tests against Beta 3, where I load 20,000 files at a time into a repo, and the pipeline which runs simply copies each file over to the output repo. (The glob pattern is `/` so all files are part of a single datum.)

Once I reach 120,000 files, the job goes into a seemingly infinite loop of restarts. 
![image](https://user-images.githubusercontent.com/15801149/127038544-6aaf9bca-719c-4be2-9bf6-ca573d5673f8.png)

It's worth pointing out that it's only at the job level that the restarts are occurring.  The pods are not restarting:
![image](https://user-images.githubusercontent.com/15801149/127027416-4dc5997c-8091-4b4d-b0ac-030133ab74c2.png)

Nor are the containers:
![image](https://user-images.githubusercontent.com/15801149/127028032-d6a37dbd-b1f0-4ee8-b128-da60155daf26.png)

I'll attach the full logs, but here are some of the highlights:

Grepping for "error" in the storage container log:
![image](https://user-images.githubusercontent.com/15801149/127034911-2481a9bc-0dc4-47ee-84de-f068cfb195bf.png)

Grepping for "error" in the user container log:
![image](https://user-images.githubusercontent.com/15801149/127035306-74dcaebb-abb9-4d86-91db-57ec9ccef949.png)

While I saw occasional behavior like this in Beta 2, I couldn't reliably reproduce it.  With Beta 3, it doesn't always necessarily happen at the 120,000 file mark, but it always happens before I reach 200,000, which means that 
I'm unable to run the performance test to completion.

[user.log](https://github.com/pachyderm/pachyderm/files/6880382/user.log)
[storage.log](https://github.com/pachyderm/pachyderm/files/6880383/storage.log)

[AB#28](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/28)

**Comment by jdoliner** [comment]
@Tryneus would you mind take a look at this if you have bandwidth? Seems like you've probably got the most context on it.

**Comment by jdoliner** [comment]
It's possible that this is just looping because it's hitting the linux limit on files in a directory. In which case this would work if you broke up the paths a little bit.

**Comment by dgeorg42** [comment]
@jdoliner - That's possible, but I tend to think not, given that both 1.13.2 and 2.0 Beta 2 were able to run these tests on the same cluster without hitting this issue.

**Comment by jdoliner** [comment]
> That's possible, but I tend to think not, given that both 1.13.2 and 2.0 Beta 2 were able to run these tests on the same cluster without hitting this issue.

Good point, seems like this must be something new that was introduced. Already got this in 2.0 blockers but that means this is definitely something we can and should fix. @brycemcanally @brendoncarroll any idea what might have changed between betas 2 and 3 that would have broken this?

**Comment by brycemcanally** [comment]
There was an issue with our pg bouncer deployment where the pool mode was not being set to transaction (the default is session). This issue was really noticeable with the asynchronous finish commit change because it would cause frequent pauses as connections to pg bouncer would timeout trying to get a postgres connection. I addressed this for beta 4 and I also refactored the job management code a bit which should improve the job resiliency. There are still some edge cases that I added TODOs for that are not correctly handled by our job management code (more info here: https://github.com/pachyderm/pachyderm/pull/6613), but a safe fallback if you get stuck is to kill the worker pods. We should retest this with beta 4, then proceed from there.

**Comment by dgeorg42** [comment]
This is still an issue in Beta 5, although the behavior is _slightly_ different. Instead of going into an infinite retry loop, the job only generates the errors once. 

From the user container log:
![image](https://user-images.githubusercontent.com/15801149/127936866-d44547b2-4614-4dd2-a7a9-e73a69f95dde.png)

From the storage container log:
![image](https://user-images.githubusercontent.com/15801149/127936938-ca2efb5f-5e33-41b0-b860-2c76dbc7b805.png)

However, the job is now stuck in a "Running" state even though it's no longer doing anything.
![image](https://user-images.githubusercontent.com/15801149/127936993-f1802299-9466-47f3-9d28-1651d677eb0c.png)

It probably should be transitioned into a "Failed" state at this point.  BUT, the larger question is: why is it failing? Why are we getting all those "file not found" errors for what appears to be FileSet metadata? And is that the root cause, or a symptom of something else?

**Comment by nitinjainsj** [comment]
@brycemcanally @brendoncarroll @PFedak I am not sure where this is getting stuck. The use case was working in Beta.2. So this has to be a recent change.
